### PR TITLE
Removed Alien Farm

### PR DESCRIPTION
**Pull request by HighlanderNetwork**
Alien Farm game has been retired and removed, further more if anyone still needs to to interact with same contract and UI, that can be found here @ cryptotomatoes.fun

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Removed in the Feb. 2020 Branch PR. Thanks for the message!

**Review by gitr0n1n — APPROVED** [review]

**Comment by gitr0n1n** [comment]
This was addressed in the last PR your merged @yaz. This can be closed.

**Review by gitr0n1n — APPROVED** [review]
Looks good.

**Comment by gitr0n1n** [comment]
@YazzyYaz decription update for a Dapp. Please merge.

**Comment by YazzyYaz** [comment]
@gitr0n1n please resolve conflicts before I can merge it

**Pull request closed without merging**
