### PR TITLE
Added new exchange (SwapSwop.io)

### PR DESCRIPTION
**Pull request by antonegorov**
Added new exchange (SwapSwop.io)

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]
Seems Legit.

**Comment by gitr0n1n** [comment]
@stevanlohja you can approve this. I guess I'm not a reviewer in this repo

**Comment by stevanlohja** [comment]
> @stevanlohja you can approve this. I guess I'm not a reviewer in this repo

There's technically a conflict. Change should be updated to go into feature branch.

**Comment by antonegorov** [comment]
Hello.
I will update the code soon and let you know.

Thanks

**Comment by antonegorov** [comment]
The Contributing.md file describes very well how I should have done everything. My mistake. My apologies.

FYI @stevanlohja: PR has been edited.

Thanks

**Review by developerkevin — APPROVED** [review]
LGTM + added to a feature branch 👍🏻

**Comment by antonegorov** [comment]
Cool! Thanks!

**Pull request merged**
